In [1]:
import numpy as np

In [14]:
# Test for np dot

x1 = np.array([[0,0,1],[0,0,1]])

x2 = np.array([[1,0,1],[1,1,0]]).T

print(np.dot(x1,x2))

[[1 0]
 [1 0]]


In [8]:
# Step 1 Collect Data
x = np.array([[0,0,1],
            [0,1,1],
            [1,0,1],
            [1,1,1]])
                
y = np.array([[0],
            [1],
            [1],
            [0]])


In [10]:
print(x.shape)

(4, 3)


In [5]:
print(y) 

[[0]
 [1]
 [1]
 [0]]


In [10]:
#Step 2 build model

num_epochs = 60000

#initialize weights
syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1

In [19]:
print syn0

[[ 5.23393541  3.54282607  1.068811    7.45325989]
 [-7.08693037  3.6701162   1.08031677 -5.88028109]
 [-2.24095703  0.03474857 -1.59660845  2.48500432]]


In [20]:
print syn1

[[ 0.95404542]
 [ 0.7290232 ]
 [-0.56594603]
 [-0.88063478]]


In [15]:
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)

    return 1/(1+np.exp(-x))

In [26]:
#Step 3 Train Model

for j in xrange(num_epochs):
    #feed forward through layers 0,1, and 2
    l0 = x
    l1 = nonlin(np.dot(l0, syn0))
    l2 = nonlin(np.dot(l1, syn1))
    
    #how much did we miss the target value?
    l2_error = y - l2
    
    if (j% 10000) == 0:
        print "Error:" + str(np.mean(np.abs(l2_error)))
    
    #in what direction is the target value?
    l2_delta = l2_error*nonlin(l2, deriv=True)
    
    #how much did each l1 value contribute to l2 error
    l1_error = l2_delta.dot(syn1.T)
    
    l1_delta= l1_error * nonlin(l1,deriv=True)
    
    syn1 += l1.T.dot(l2_delta)
    syn0 += l0.T.dot(l1_delta)

Error:0.500034425703
Error:0.0105610594438
Error:0.00728096567919
Error:0.00587594584257
Error:0.00505130438013
Error:0.00449390651769


In [22]:
print(30000 % 10000)

0
