# Anna KaRNNa

In this notebook, I'll build a character-wise RNN trained on Anna Karenina, one of my all-time favorite books. It'll be able to generate new text based on the text from the book.

This network is based off of Andrej Karpathy's [post on RNNs](http://karpathy.github.io/2015/05/21/rnn-effectiveness/) and [implementation in Torch](https://github.com/karpathy/char-rnn). Also, some information [here at r2rt](http://r2rt.com/recurrent-neural-networks-in-tensorflow-ii.html) and from [Sherjil Ozair](https://github.com/sherjilozair/char-rnn-tensorflow) on GitHub. Below is the general architecture of the character-wise RNN.

<img src="assets/charseq.jpeg" width="500">

In [1]:
import time
from collections import namedtuple

import numpy as np
import tensorflow as tf

First we'll load the text file and convert it into integers for our network to use. Here I'm creating a couple dictionaries to convert the characters to and from integers. Encoding the characters as integers makes it easier to use as input in the network.

In [2]:
with open('anna.txt', 'r') as f:
    text=f.read()
vocab = set(text)
vocab_to_int = {c: i for i, c in enumerate(vocab)}
int_to_vocab = dict(enumerate(vocab))
encoded = np.array([vocab_to_int[c] for c in text], dtype=np.int32)

Let's check out the first 100 characters, make sure everything is peachy. According to the [American Book Review](http://americanbookreview.org/100bestlines.asp), this is the 6th best first line of a book ever.

In [3]:
text[:100]

'Chapter 1\n\n\nHappy families are all alike; every unhappy family is unhappy in its own\nway.\n\nEverythin'

And we can see the characters encoded as integers.

In [4]:
encoded[:100]

array([81, 45, 11, 73, 12, 38, 18, 44, 40, 28, 28, 28, 70, 11, 73, 73, 15,
       44, 21, 11, 19, 24, 25, 24, 38, 46, 44, 11, 18, 38, 44, 11, 25, 25,
       44, 11, 25, 24, 66, 38, 16, 44, 38, 39, 38, 18, 15, 44, 57, 10, 45,
       11, 73, 73, 15, 44, 21, 11, 19, 24, 25, 15, 44, 24, 46, 44, 57, 10,
       45, 11, 73, 73, 15, 44, 24, 10, 44, 24, 12, 46, 44, 58, 43, 10, 28,
       43, 11, 15, 13, 28, 28, 53, 39, 38, 18, 15, 12, 45, 24, 10], dtype=int32)

Since the network is working with individual characters, it's similar to a classification problem in which we are trying to predict the next character from the previous text.  Here's how many 'classes' our network has to pick from.

In [5]:
len(vocab)

83

## Making training mini-batches

Here is where we'll make our mini-batches for training. Remember that we want our batches to be multiple sequences of some desired number of sequence steps. Considering a simple example, our batches would look like this:

<img src="assets/sequence_batching@1x.png" width=500px>


<br>
We have our text encoded as integers as one long array in `encoded`. Let's create a function that will give us an iterator for our batches. I like using [generator functions](https://jeffknupp.com/blog/2013/04/07/improve-your-python-yield-and-generators-explained/) to do this. Then we can pass `encoded` into this function and get our batch generator.

The first thing we need to do is discard some of the text so we only have completely full batches. Each batch contains $N \times M$ characters, where $N$ is the batch size (the number of sequences) and $M$ is the number of steps. Then, to get the number of batches we can make from some array `arr`, you divide the length of `arr` by the batch size. Once you know the number of batches and the batch size, you can get the total number of characters to keep.

After that, we need to split `arr` into $N$ sequences. You can do this using `arr.reshape(size)` where `size` is a tuple containing the dimensions sizes of the reshaped array. We know we want $N$ sequences (`n_seqs` below), let's make that the size of the first dimension. For the second dimension, you can use `-1` as a placeholder in the size, it'll fill up the array with the appropriate data for you. After this, you should have an array that is $N \times (M * K)$ where $K$ is the number of batches.

Now that we have this array, we can iterate through it to get our batches. The idea is each batch is a $N \times M$ window on the array. For each subsequent batch, the window moves over by `n_steps`. We also want to create both the input and target arrays. Remember that the targets are the inputs shifted over one character. You'll usually see the first input character used as the last target character, so something like this:
```python
y[:, :-1], y[:, -1] = x[:, 1:], x[:, 0]
```
where `x` is the input batch and `y` is the target batch.

The way I like to do this window is use `range` to take steps of size `n_steps` from $0$ to `arr.shape[1]`, the total number of steps in each sequence. That way, the integers you get from `range` always point to the start of a batch, and each window is `n_steps` wide.

In [6]:
def get_batches(arr, n_seqs, n_steps):
    '''Create a generator that returns batches of size
       n_seqs x n_steps from arr.
       
       Arguments
       ---------
       arr: Array you want to make batches from
       n_seqs: Batch size, the number of sequences per batch
       n_steps: Number of sequence steps per batch
    '''
    # Get the number of characters per batch and number of batches we can make
    characters_per_batch = n_seqs * n_steps
    n_batches = len(arr)//characters_per_batch
    
    # Keep only enough characters to make full batches
    arr = arr[:n_batches * characters_per_batch]
    
    # Reshape into n_seqs rows
    arr = arr.reshape((n_seqs, -1))
    
    for n in range(0, arr.shape[1], n_steps):
        # The features
        x = arr[:, n:n+n_steps]
        # The targets, shifted by one
        y = np.zeros_like(x)
        y[:, :-1], y[:, -1] = x[:, 1:], x[:, 0]
        yield x, y

Now I'll make my data sets and we can check out what's going on here. Here I'm going to use a batch size of 10 and 50 sequence steps.

In [7]:
batches = get_batches(encoded, 10, 50)
x, y = next(batches)

In [8]:
print('x\n', x[:10, :10])
print('\ny\n', y[:10, :10])

x
 [[81 45 11 73 12 38 18 44 40 28]
 [44 11 19 44 10 58 12 44 41 58]
 [39 24 10 13 28 28 65 35 38 46]
 [10 44  5 57 18 24 10 41 44 45]
 [44 24 12 44 24 46  9 44 46 24]
 [44 17 12 44 43 11 46 28 58 10]
 [45 38 10 44 30 58 19 38 44 21]
 [16 44 76 57 12 44 10 58 43 44]
 [12 44 24 46 10 82 12 13 44 14]
 [44 46 11 24  5 44 12 58 44 45]]

y
 [[45 11 73 12 38 18 44 40 28 28]
 [11 19 44 10 58 12 44 41 58 24]
 [24 10 13 28 28 65 35 38 46  9]
 [44  5 57 18 24 10 41 44 45 24]
 [24 12 44 24 46  9 44 46 24 18]
 [17 12 44 43 11 46 28 58 10 25]
 [38 10 44 30 58 19 38 44 21 58]
 [44 76 57 12 44 10 58 43 44 46]
 [44 24 46 10 82 12 13 44 14 45]
 [46 11 24  5 44 12 58 44 45 38]]


If you implemented `get_batches` correctly, the above output should look something like 
```
x
 [[55 63 69 22  6 76 45  5 16 35]
 [ 5 69  1  5 12 52  6  5 56 52]
 [48 29 12 61 35 35  8 64 76 78]
 [12  5 24 39 45 29 12 56  5 63]
 [ 5 29  6  5 29 78 28  5 78 29]
 [ 5 13  6  5 36 69 78 35 52 12]
 [63 76 12  5 18 52  1 76  5 58]
 [34  5 73 39  6  5 12 52 36  5]
 [ 6  5 29 78 12 79  6 61  5 59]
 [ 5 78 69 29 24  5  6 52  5 63]]

y
 [[63 69 22  6 76 45  5 16 35 35]
 [69  1  5 12 52  6  5 56 52 29]
 [29 12 61 35 35  8 64 76 78 28]
 [ 5 24 39 45 29 12 56  5 63 29]
 [29  6  5 29 78 28  5 78 29 45]
 [13  6  5 36 69 78 35 52 12 43]
 [76 12  5 18 52  1 76  5 58 52]
 [ 5 73 39  6  5 12 52 36  5 78]
 [ 5 29 78 12 79  6 61  5 59 63]
 [78 69 29 24  5  6 52  5 63 76]]
 ```
 although the exact numbers will be different. Check to make sure the data is shifted over one step for `y`.

## Building the model

Below is where you'll build the network. We'll break it up into parts so it's easier to reason about each bit. Then we can connect them up into the whole network.

<img src="assets/charRNN.png" width=500px>


### Inputs

First off we'll create our input placeholders. As usual we need placeholders for the training data and the targets. We'll also create a placeholder for dropout layers called `keep_prob`.

In [9]:
def build_inputs(batch_size, num_steps):
    ''' Define placeholders for inputs, targets, and dropout 
    
        Arguments
        ---------
        batch_size: Batch size, number of sequences per batch
        num_steps: Number of sequence steps in a batch
        
    '''
    # Declare placeholders we'll feed into the graph
    inputs = tf.placeholder(tf.int32, [batch_size, num_steps], name='inputs')
    targets = tf.placeholder(tf.int32, [batch_size, num_steps], name='targets')
    
    # Keep probability placeholder for drop out layers
    keep_prob = tf.placeholder(tf.float32, name='keep_prob')
    
    return inputs, targets, keep_prob

### LSTM Cell

Here we will create the LSTM cell we'll use in the hidden layer. We'll use this cell as a building block for the RNN. So we aren't actually defining the RNN here, just the type of cell we'll use in the hidden layer.

We first create a basic LSTM cell with

```python
lstm = tf.contrib.rnn.BasicLSTMCell(num_units)
```

where `num_units` is the number of units in the hidden layers in the cell. Then we can add dropout by wrapping it with 

```python
tf.contrib.rnn.DropoutWrapper(lstm, output_keep_prob=keep_prob)
```
You pass in a cell and it will automatically add dropout to the inputs or outputs. Finally, we can stack up the LSTM cells into layers with [`tf.contrib.rnn.MultiRNNCell`](https://www.tensorflow.org/versions/r1.0/api_docs/python/tf/contrib/rnn/MultiRNNCell). With this, you pass in a list of cells and it will send the output of one cell into the next cell. Previously with TensorFlow 1.0, you could do this

```python
tf.contrib.rnn.MultiRNNCell([cell]*num_layers)
```

This might look a little weird if you know Python well because this will create a list of the same `cell` object. However, TensorFlow 1.0 will create different weight matrices for all `cell` objects. But, starting with TensorFlow 1.1 you actually need to create new cell objects in the list. To get it to work in TensorFlow 1.1, it should look like

```python
def build_cell(num_units, keep_prob):
    lstm = tf.contrib.rnn.BasicLSTMCell(num_units)
    drop = tf.contrib.rnn.DropoutWrapper(lstm, output_keep_prob=keep_prob)
    
    return drop
    
tf.contrib.rnn.MultiRNNCell([build_cell(num_units, keep_prob) for _ in range(num_layers)])
```

Even though this is actually multiple LSTM cells stacked on each other, you can treat the multiple layers as one cell.

We also need to create an initial cell state of all zeros. This can be done like so

```python
initial_state = cell.zero_state(batch_size, tf.float32)
```

Below, we implement the `build_lstm` function to create these LSTM cells and the initial state.

In [10]:
def build_lstm(lstm_size, num_layers, batch_size, keep_prob):
    ''' Build LSTM cell.
    
        Arguments
        ---------
        keep_prob: Scalar tensor (tf.placeholder) for the dropout keep probability
        lstm_size: Size of the hidden layers in the LSTM cells
        num_layers: Number of LSTM layers
        batch_size: Batch size

    '''
    ### Build the LSTM Cell
    
    def build_cell(lstm_size, keep_prob):
        # Use a basic LSTM cell
        lstm = tf.contrib.rnn.BasicLSTMCell(lstm_size)
        
        # Add dropout to the cell
        drop = tf.contrib.rnn.DropoutWrapper(lstm, output_keep_prob=keep_prob)
        return drop
    
    
    # Stack up multiple LSTM layers, for deep learning
    cell = tf.contrib.rnn.MultiRNNCell([build_cell(lstm_size, keep_prob) for _ in range(num_layers)])
    initial_state = cell.zero_state(batch_size, tf.float32)
    
    return cell, initial_state

### RNN Output

Here we'll create the output layer. We need to connect the output of the RNN cells to a full connected layer with a softmax output. The softmax output gives us a probability distribution we can use to predict the next character.

If our input has batch size $N$, number of steps $M$, and the hidden layer has $L$ hidden units, then the output is a 3D tensor with size $N \times M \times L$. The output of each LSTM cell has size $L$, we have $M$ of them, one for each sequence step, and we have $N$ sequences. So the total size is $N \times M \times L$.

We are using the same fully connected layer, the same weights, for each of the outputs. Then, to make things easier, we should reshape the outputs into a 2D tensor with shape $(M * N) \times L$. That is, one row for each sequence and step, where the values of each row are the output from the LSTM cells.

One we have the outputs reshaped, we can do the matrix multiplication with the weights. We need to wrap the weight and bias variables in a variable scope with `tf.variable_scope(scope_name)` because there are weights being created in the LSTM cells. TensorFlow will throw an error if the weights created here have the same names as the weights created in the LSTM cells, which they will be default. To avoid this, we wrap the variables in a variable scope so we can give them unique names.

In [11]:
def build_output(lstm_output, in_size, out_size):
    ''' Build a softmax layer, return the softmax output and logits.
    
        Arguments
        ---------
        
        x: Input tensor
        in_size: Size of the input tensor, for example, size of the LSTM cells
        out_size: Size of this softmax layer
    
    '''

    # Reshape output so it's a bunch of rows, one row for each step for each sequence.
    # That is, the shape should be batch_size*num_steps rows by lstm_size columns
    seq_output = tf.concat(lstm_output, axis=1)
    x = tf.reshape(seq_output, [-1, in_size])
    
    # Connect the RNN outputs to a softmax layer
    with tf.variable_scope('softmax'):
        softmax_w = tf.Variable(tf.truncated_normal((in_size, out_size), stddev=0.1))
        softmax_b = tf.Variable(tf.zeros(out_size))
    
    # Since output is a bunch of rows of RNN cell outputs, logits will be a bunch
    # of rows of logit outputs, one for each step and sequence
    logits = tf.matmul(x, softmax_w) + softmax_b
    
    # Use softmax to get the probabilities for predicted characters
    out = tf.nn.softmax(logits, name='predictions')
    
    return out, logits

### Training loss

Next up is the training loss. We get the logits and targets and calculate the softmax cross-entropy loss. First we need to one-hot encode the targets, we're getting them as encoded characters. Then, reshape the one-hot targets so it's a 2D tensor with size $(M*N) \times C$ where $C$ is the number of classes/characters we have. Remember that we reshaped the LSTM outputs and ran them through a fully connected layer with $C$ units. So our logits will also have size $(M*N) \times C$.

Then we run the logits and targets through `tf.nn.softmax_cross_entropy_with_logits` and find the mean to get the loss.

In [12]:
def build_loss(logits, targets, lstm_size, num_classes):
    ''' Calculate the loss from the logits and the targets.
    
        Arguments
        ---------
        logits: Logits from final fully connected layer
        targets: Targets for supervised learning
        lstm_size: Number of LSTM hidden units
        num_classes: Number of classes in targets
        
    '''
    
    # One-hot encode targets and reshape to match logits, one row per batch_size per step
    y_one_hot = tf.one_hot(targets, num_classes)
    y_reshaped = tf.reshape(y_one_hot, logits.get_shape())
    
    # Softmax cross entropy loss
    loss = tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels=y_reshaped)
    loss = tf.reduce_mean(loss)
    return loss

### Optimizer

Here we build the optimizer. Normal RNNs have have issues gradients exploding and disappearing. LSTMs fix the disappearance problem, but the gradients can still grow without bound. To fix this, we can clip the gradients above some threshold. That is, if a gradient is larger than that threshold, we set it to the threshold. This will ensure the gradients never grow overly large. Then we use an AdamOptimizer for the learning step.

In [13]:
def build_optimizer(loss, learning_rate, grad_clip):
    ''' Build optmizer for training, using gradient clipping.
    
        Arguments:
        loss: Network loss
        learning_rate: Learning rate for optimizer
    
    '''
    
    # Optimizer for training, using gradient clipping to control exploding gradients
    tvars = tf.trainable_variables()
    grads, _ = tf.clip_by_global_norm(tf.gradients(loss, tvars), grad_clip)
    train_op = tf.train.AdamOptimizer(learning_rate)
    optimizer = train_op.apply_gradients(zip(grads, tvars))
    
    return optimizer

### Build the network

Now we can put all the pieces together and build a class for the network. To actually run data through the LSTM cells, we will use [`tf.nn.dynamic_rnn`](https://www.tensorflow.org/versions/r1.0/api_docs/python/tf/nn/dynamic_rnn). This function will pass the hidden and cell states across LSTM cells appropriately for us. It returns the outputs for each LSTM cell at each step for each sequence in the mini-batch. It also gives us the final LSTM state. We want to save this state as `final_state` so we can pass it to the first LSTM cell in the the next mini-batch run. For `tf.nn.dynamic_rnn`, we pass in the cell and initial state we get from `build_lstm`, as well as our input sequences. Also, we need to one-hot encode the inputs before going into the RNN. 

In [14]:
class CharRNN:
    
    def __init__(self, num_classes, batch_size=64, num_steps=50, 
                       lstm_size=128, num_layers=2, learning_rate=0.001, 
                       grad_clip=5, sampling=False):
    
        # When we're using this network for sampling later, we'll be passing in
        # one character at a time, so providing an option for that
        if sampling == True:
            batch_size, num_steps = 1, 1
        else:
            batch_size, num_steps = batch_size, num_steps

        tf.reset_default_graph()
        
        # Build the input placeholder tensors
        self.inputs, self.targets, self.keep_prob = build_inputs(batch_size, num_steps)

        # Build the LSTM cell
        cell, self.initial_state = build_lstm(lstm_size, num_layers, batch_size, self.keep_prob)

        ### Run the data through the RNN layers
        # First, one-hot encode the input tokens
        x_one_hot = tf.one_hot(self.inputs, num_classes)
        
        # Run each sequence step through the RNN and collect the outputs
        outputs, state = tf.nn.dynamic_rnn(cell, x_one_hot, initial_state=self.initial_state)
        self.final_state = state
        
        # Get softmax predictions and logits
        self.prediction, self.logits = build_output(outputs, lstm_size, num_classes)
        
        # Loss and optimizer (with gradient clipping)
        self.loss = build_loss(self.logits, self.targets, lstm_size, num_classes)
        self.optimizer = build_optimizer(self.loss, learning_rate, grad_clip)

## Hyperparameters

Here I'm defining the hyperparameters for the network. 

* `batch_size` - Number of sequences running through the network in one pass.
* `num_steps` - Number of characters in the sequence the network is trained on. Larger is better typically, the network will learn more long range dependencies. But it takes longer to train. 100 is typically a good number here.
* `lstm_size` - The number of units in the hidden layers.
* `num_layers` - Number of hidden LSTM layers to use
* `learning_rate` - Learning rate for training
* `keep_prob` - The dropout keep probability when training. If you're network is overfitting, try decreasing this.

Here's some good advice from Andrej Karpathy on training the network. I'm going to copy it in here for your benefit, but also link to [where it originally came from](https://github.com/karpathy/char-rnn#tips-and-tricks).

> ## Tips and Tricks

>### Monitoring Validation Loss vs. Training Loss
>If you're somewhat new to Machine Learning or Neural Networks it can take a bit of expertise to get good models. The most important quantity to keep track of is the difference between your training loss (printed during training) and the validation loss (printed once in a while when the RNN is run on the validation data (by default every 1000 iterations)). In particular:

> - If your training loss is much lower than validation loss then this means the network might be **overfitting**. Solutions to this are to decrease your network size, or to increase dropout. For example you could try dropout of 0.5 and so on.
> - If your training/validation loss are about equal then your model is **underfitting**. Increase the size of your model (either number of layers or the raw number of neurons per layer)

> ### Approximate number of parameters

> The two most important parameters that control the model are `lstm_size` and `num_layers`. I would advise that you always use `num_layers` of either 2/3. The `lstm_size` can be adjusted based on how much data you have. The two important quantities to keep track of here are:

> - The number of parameters in your model. This is printed when you start training.
> - The size of your dataset. 1MB file is approximately 1 million characters.

>These two should be about the same order of magnitude. It's a little tricky to tell. Here are some examples:

> - I have a 100MB dataset and I'm using the default parameter settings (which currently print 150K parameters). My data size is significantly larger (100 mil >> 0.15 mil), so I expect to heavily underfit. I am thinking I can comfortably afford to make `lstm_size` larger.
> - I have a 10MB dataset and running a 10 million parameter model. I'm slightly nervous and I'm carefully monitoring my validation loss. If it's larger than my training loss then I may want to try to increase dropout a bit and see if that helps the validation loss.

> ### Best models strategy

>The winning strategy to obtaining very good models (if you have the compute time) is to always err on making the network larger (as large as you're willing to wait for it to compute) and then try different dropout values (between 0,1). Whatever model has the best validation performance (the loss, written in the checkpoint filename, low is good) is the one you should use in the end.

>It is very common in deep learning to run many different models with many different hyperparameter settings, and in the end take whatever checkpoint gave the best validation performance.

>By the way, the size of your training and validation splits are also parameters. Make sure you have a decent amount of data in your validation set or otherwise the validation performance will be noisy and not very informative.


In [15]:
batch_size = 100        # Sequences per batch
num_steps = 100         # Number of sequence steps per batch
lstm_size = 512         # Size of hidden layers in LSTMs
num_layers = 2          # Number of LSTM layers
learning_rate = 0.001   # Learning rate
keep_prob = 0.5         # Dropout keep probability

## Time for training

This is typical training code, passing inputs and targets into the network, then running the optimizer. Here we also get back the final LSTM state for the mini-batch. Then, we pass that state back into the network so the next batch can continue the state from the previous batch. And every so often (set by `save_every_n`) I save a checkpoint.

Here I'm saving checkpoints with the format

`i{iteration number}_l{# hidden layer units}.ckpt`

In [17]:
epochs = 20
# Save every N iterations
save_every_n = 200

model = CharRNN(len(vocab), batch_size=batch_size, num_steps=num_steps,
                lstm_size=lstm_size, num_layers=num_layers, 
                learning_rate=learning_rate)

saver = tf.train.Saver(max_to_keep=100)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    # Use the line below to load a checkpoint and resume training
    #saver.restore(sess, 'checkpoints/______.ckpt')
    counter = 0
    for e in range(epochs):
        # Train network
        new_state = sess.run(model.initial_state)
        loss = 0
        for x, y in get_batches(encoded, batch_size, num_steps):
            counter += 1
            start = time.time()
            feed = {model.inputs: x,
                    model.targets: y,
                    model.keep_prob: keep_prob,
                    model.initial_state: new_state}
            batch_loss, new_state, _ = sess.run([model.loss, 
                                                 model.final_state, 
                                                 model.optimizer], 
                                                 feed_dict=feed)
            
            end = time.time()
            print('Epoch: {}/{}... '.format(e+1, epochs),
                  'Training Step: {}... '.format(counter),
                  'Training loss: {:.4f}... '.format(batch_loss),
                  '{:.4f} sec/batch'.format((end-start)))
        
            if (counter % save_every_n == 0):
                saver.save(sess, "checkpoints/i{}_l{}.ckpt".format(counter, lstm_size))
    
    saver.save(sess, "checkpoints/i{}_l{}.ckpt".format(counter, lstm_size))

Epoch: 1/20...  Training Step: 1...  Training loss: 4.4153...  3.8992 sec/batch
Epoch: 1/20...  Training Step: 2...  Training loss: 4.3184...  3.9753 sec/batch
Epoch: 1/20...  Training Step: 3...  Training loss: 3.7851...  3.7467 sec/batch
Epoch: 1/20...  Training Step: 4...  Training loss: 3.9203...  3.5029 sec/batch
Epoch: 1/20...  Training Step: 5...  Training loss: 3.5875...  3.4589 sec/batch
Epoch: 1/20...  Training Step: 6...  Training loss: 3.5226...  3.4331 sec/batch
Epoch: 1/20...  Training Step: 7...  Training loss: 3.4483...  3.4780 sec/batch
Epoch: 1/20...  Training Step: 8...  Training loss: 3.4605...  3.4861 sec/batch
Epoch: 1/20...  Training Step: 9...  Training loss: 3.3784...  3.3648 sec/batch
Epoch: 1/20...  Training Step: 10...  Training loss: 3.3275...  3.4637 sec/batch
Epoch: 1/20...  Training Step: 11...  Training loss: 3.3078...  3.6536 sec/batch
Epoch: 1/20...  Training Step: 12...  Training loss: 3.2977...  3.5053 sec/batch
Epoch: 1/20...  Training Step: 13... 

Epoch: 1/20...  Training Step: 103...  Training loss: 2.9375...  3.9180 sec/batch
Epoch: 1/20...  Training Step: 104...  Training loss: 2.9187...  3.8488 sec/batch
Epoch: 1/20...  Training Step: 105...  Training loss: 2.9158...  3.8498 sec/batch
Epoch: 1/20...  Training Step: 106...  Training loss: 2.9107...  3.7702 sec/batch
Epoch: 1/20...  Training Step: 107...  Training loss: 2.8655...  3.7943 sec/batch
Epoch: 1/20...  Training Step: 108...  Training loss: 2.8935...  3.9826 sec/batch
Epoch: 1/20...  Training Step: 109...  Training loss: 2.9120...  3.8052 sec/batch
Epoch: 1/20...  Training Step: 110...  Training loss: 2.8647...  4.1925 sec/batch
Epoch: 1/20...  Training Step: 111...  Training loss: 2.8591...  4.0982 sec/batch
Epoch: 1/20...  Training Step: 112...  Training loss: 2.8684...  4.0969 sec/batch
Epoch: 1/20...  Training Step: 113...  Training loss: 2.8497...  4.1923 sec/batch
Epoch: 1/20...  Training Step: 114...  Training loss: 2.8187...  4.0666 sec/batch
Epoch: 1/20...  

Epoch: 2/20...  Training Step: 203...  Training loss: 2.3612...  3.9459 sec/batch
Epoch: 2/20...  Training Step: 204...  Training loss: 2.3455...  4.0074 sec/batch
Epoch: 2/20...  Training Step: 205...  Training loss: 2.3472...  4.2551 sec/batch
Epoch: 2/20...  Training Step: 206...  Training loss: 2.3575...  3.8812 sec/batch
Epoch: 2/20...  Training Step: 207...  Training loss: 2.3771...  3.8894 sec/batch
Epoch: 2/20...  Training Step: 208...  Training loss: 2.3395...  3.9153 sec/batch
Epoch: 2/20...  Training Step: 209...  Training loss: 2.3283...  3.9255 sec/batch
Epoch: 2/20...  Training Step: 210...  Training loss: 2.3410...  3.8478 sec/batch
Epoch: 2/20...  Training Step: 211...  Training loss: 2.3414...  3.9066 sec/batch
Epoch: 2/20...  Training Step: 212...  Training loss: 2.3766...  4.0667 sec/batch
Epoch: 2/20...  Training Step: 213...  Training loss: 2.3450...  3.9295 sec/batch
Epoch: 2/20...  Training Step: 214...  Training loss: 2.3350...  3.8572 sec/batch
Epoch: 2/20...  

Epoch: 2/20...  Training Step: 303...  Training loss: 2.1317...  4.1096 sec/batch
Epoch: 2/20...  Training Step: 304...  Training loss: 2.1276...  3.9705 sec/batch
Epoch: 2/20...  Training Step: 305...  Training loss: 2.1212...  3.9849 sec/batch
Epoch: 2/20...  Training Step: 306...  Training loss: 2.1476...  3.9541 sec/batch
Epoch: 2/20...  Training Step: 307...  Training loss: 2.1386...  4.1502 sec/batch
Epoch: 2/20...  Training Step: 308...  Training loss: 2.1225...  3.9911 sec/batch
Epoch: 2/20...  Training Step: 309...  Training loss: 2.1347...  4.1746 sec/batch
Epoch: 2/20...  Training Step: 310...  Training loss: 2.1318...  4.0674 sec/batch
Epoch: 2/20...  Training Step: 311...  Training loss: 2.1260...  4.0303 sec/batch
Epoch: 2/20...  Training Step: 312...  Training loss: 2.1131...  4.0879 sec/batch
Epoch: 2/20...  Training Step: 313...  Training loss: 2.1046...  4.0922 sec/batch
Epoch: 2/20...  Training Step: 314...  Training loss: 2.0809...  4.0836 sec/batch
Epoch: 2/20...  

Epoch: 3/20...  Training Step: 403...  Training loss: 2.0019...  3.9773 sec/batch
Epoch: 3/20...  Training Step: 404...  Training loss: 1.9928...  4.0140 sec/batch
Epoch: 3/20...  Training Step: 405...  Training loss: 2.0335...  4.0136 sec/batch
Epoch: 3/20...  Training Step: 406...  Training loss: 1.9989...  3.9757 sec/batch
Epoch: 3/20...  Training Step: 407...  Training loss: 1.9679...  2.5429 sec/batch
Epoch: 3/20...  Training Step: 408...  Training loss: 1.9828...  4.0524 sec/batch
Epoch: 3/20...  Training Step: 409...  Training loss: 1.9820...  4.0424 sec/batch
Epoch: 3/20...  Training Step: 410...  Training loss: 2.0227...  3.9904 sec/batch
Epoch: 3/20...  Training Step: 411...  Training loss: 1.9772...  4.0115 sec/batch
Epoch: 3/20...  Training Step: 412...  Training loss: 1.9725...  4.0138 sec/batch
Epoch: 3/20...  Training Step: 413...  Training loss: 1.9808...  3.9833 sec/batch
Epoch: 3/20...  Training Step: 414...  Training loss: 2.0321...  3.9813 sec/batch
Epoch: 3/20...  

Epoch: 3/20...  Training Step: 503...  Training loss: 1.8717...  4.9515 sec/batch
Epoch: 3/20...  Training Step: 504...  Training loss: 1.8910...  4.0536 sec/batch
Epoch: 3/20...  Training Step: 505...  Training loss: 1.8915...  4.0701 sec/batch
Epoch: 3/20...  Training Step: 506...  Training loss: 1.8868...  4.0204 sec/batch
Epoch: 3/20...  Training Step: 507...  Training loss: 1.8676...  4.1489 sec/batch
Epoch: 3/20...  Training Step: 508...  Training loss: 1.8637...  4.0335 sec/batch
Epoch: 3/20...  Training Step: 509...  Training loss: 1.8702...  4.0268 sec/batch
Epoch: 3/20...  Training Step: 510...  Training loss: 1.8649...  4.0409 sec/batch
Epoch: 3/20...  Training Step: 511...  Training loss: 1.8457...  4.0521 sec/batch
Epoch: 3/20...  Training Step: 512...  Training loss: 1.8340...  4.0078 sec/batch
Epoch: 3/20...  Training Step: 513...  Training loss: 1.8698...  4.0185 sec/batch
Epoch: 3/20...  Training Step: 514...  Training loss: 1.8543...  4.0051 sec/batch
Epoch: 3/20...  

Epoch: 4/20...  Training Step: 603...  Training loss: 1.8324...  4.1194 sec/batch
Epoch: 4/20...  Training Step: 604...  Training loss: 1.7994...  4.1309 sec/batch
Epoch: 4/20...  Training Step: 605...  Training loss: 1.7823...  4.0964 sec/batch
Epoch: 4/20...  Training Step: 606...  Training loss: 1.7810...  4.0396 sec/batch
Epoch: 4/20...  Training Step: 607...  Training loss: 1.7986...  4.0978 sec/batch
Epoch: 4/20...  Training Step: 608...  Training loss: 1.8300...  4.1825 sec/batch
Epoch: 4/20...  Training Step: 609...  Training loss: 1.7934...  4.0678 sec/batch
Epoch: 4/20...  Training Step: 610...  Training loss: 1.7779...  4.0162 sec/batch
Epoch: 4/20...  Training Step: 611...  Training loss: 1.7969...  4.0597 sec/batch
Epoch: 4/20...  Training Step: 612...  Training loss: 1.8242...  4.1601 sec/batch
Epoch: 4/20...  Training Step: 613...  Training loss: 1.8042...  4.0796 sec/batch
Epoch: 4/20...  Training Step: 614...  Training loss: 1.8094...  4.0818 sec/batch
Epoch: 4/20...  

Epoch: 4/20...  Training Step: 703...  Training loss: 1.7206...  3.8180 sec/batch
Epoch: 4/20...  Training Step: 704...  Training loss: 1.7256...  3.8350 sec/batch
Epoch: 4/20...  Training Step: 705...  Training loss: 1.7173...  3.8177 sec/batch
Epoch: 4/20...  Training Step: 706...  Training loss: 1.7152...  3.8673 sec/batch
Epoch: 4/20...  Training Step: 707...  Training loss: 1.7077...  3.7826 sec/batch
Epoch: 4/20...  Training Step: 708...  Training loss: 1.7022...  3.8443 sec/batch
Epoch: 4/20...  Training Step: 709...  Training loss: 1.6991...  3.8205 sec/batch
Epoch: 4/20...  Training Step: 710...  Training loss: 1.6772...  3.7405 sec/batch
Epoch: 4/20...  Training Step: 711...  Training loss: 1.7218...  3.8257 sec/batch
Epoch: 4/20...  Training Step: 712...  Training loss: 1.6983...  3.7924 sec/batch
Epoch: 4/20...  Training Step: 713...  Training loss: 1.7130...  4.5369 sec/batch
Epoch: 4/20...  Training Step: 714...  Training loss: 1.6978...  3.8370 sec/batch
Epoch: 4/20...  

Epoch: 5/20...  Training Step: 803...  Training loss: 1.6456...  3.7999 sec/batch
Epoch: 5/20...  Training Step: 804...  Training loss: 1.6471...  3.8893 sec/batch
Epoch: 5/20...  Training Step: 805...  Training loss: 1.6591...  4.5384 sec/batch
Epoch: 5/20...  Training Step: 806...  Training loss: 1.7134...  3.8140 sec/batch
Epoch: 5/20...  Training Step: 807...  Training loss: 1.6539...  3.8520 sec/batch
Epoch: 5/20...  Training Step: 808...  Training loss: 1.6522...  3.7901 sec/batch
Epoch: 5/20...  Training Step: 809...  Training loss: 1.6777...  3.8885 sec/batch
Epoch: 5/20...  Training Step: 810...  Training loss: 1.6946...  3.7853 sec/batch
Epoch: 5/20...  Training Step: 811...  Training loss: 1.6786...  3.8378 sec/batch
Epoch: 5/20...  Training Step: 812...  Training loss: 1.6837...  3.8900 sec/batch
Epoch: 5/20...  Training Step: 813...  Training loss: 1.6387...  4.0958 sec/batch
Epoch: 5/20...  Training Step: 814...  Training loss: 1.6794...  3.8192 sec/batch
Epoch: 5/20...  

Epoch: 5/20...  Training Step: 903...  Training loss: 1.6022...  3.9000 sec/batch
Epoch: 5/20...  Training Step: 904...  Training loss: 1.6097...  3.7680 sec/batch
Epoch: 5/20...  Training Step: 905...  Training loss: 1.6189...  4.0563 sec/batch
Epoch: 5/20...  Training Step: 906...  Training loss: 1.5966...  3.9261 sec/batch
Epoch: 5/20...  Training Step: 907...  Training loss: 1.5848...  3.8595 sec/batch
Epoch: 5/20...  Training Step: 908...  Training loss: 1.5731...  3.8796 sec/batch
Epoch: 5/20...  Training Step: 909...  Training loss: 1.6301...  3.7905 sec/batch
Epoch: 5/20...  Training Step: 910...  Training loss: 1.6006...  3.8710 sec/batch
Epoch: 5/20...  Training Step: 911...  Training loss: 1.5975...  3.7446 sec/batch
Epoch: 5/20...  Training Step: 912...  Training loss: 1.6031...  3.7861 sec/batch
Epoch: 5/20...  Training Step: 913...  Training loss: 1.6119...  4.4824 sec/batch
Epoch: 5/20...  Training Step: 914...  Training loss: 1.5741...  3.7855 sec/batch
Epoch: 5/20...  

Epoch: 6/20...  Training Step: 1003...  Training loss: 1.5649...  4.7755 sec/batch
Epoch: 6/20...  Training Step: 1004...  Training loss: 1.6025...  4.7644 sec/batch
Epoch: 6/20...  Training Step: 1005...  Training loss: 1.5666...  4.8187 sec/batch
Epoch: 6/20...  Training Step: 1006...  Training loss: 1.5500...  4.7426 sec/batch
Epoch: 6/20...  Training Step: 1007...  Training loss: 1.5910...  4.7909 sec/batch
Epoch: 6/20...  Training Step: 1008...  Training loss: 1.5969...  4.8274 sec/batch
Epoch: 6/20...  Training Step: 1009...  Training loss: 1.5782...  4.7760 sec/batch
Epoch: 6/20...  Training Step: 1010...  Training loss: 1.6032...  4.7698 sec/batch
Epoch: 6/20...  Training Step: 1011...  Training loss: 1.5632...  5.1520 sec/batch
Epoch: 6/20...  Training Step: 1012...  Training loss: 1.5922...  6.1178 sec/batch
Epoch: 6/20...  Training Step: 1013...  Training loss: 1.5589...  5.2745 sec/batch
Epoch: 6/20...  Training Step: 1014...  Training loss: 1.5790...  4.7126 sec/batch
Epoc

Epoch: 6/20...  Training Step: 1102...  Training loss: 1.5377...  4.9443 sec/batch
Epoch: 6/20...  Training Step: 1103...  Training loss: 1.5410...  4.8433 sec/batch
Epoch: 6/20...  Training Step: 1104...  Training loss: 1.5230...  4.8446 sec/batch
Epoch: 6/20...  Training Step: 1105...  Training loss: 1.5141...  4.8750 sec/batch
Epoch: 6/20...  Training Step: 1106...  Training loss: 1.5016...  4.8620 sec/batch
Epoch: 6/20...  Training Step: 1107...  Training loss: 1.5404...  4.8777 sec/batch
Epoch: 6/20...  Training Step: 1108...  Training loss: 1.5442...  5.3730 sec/batch
Epoch: 6/20...  Training Step: 1109...  Training loss: 1.5387...  6.2462 sec/batch
Epoch: 6/20...  Training Step: 1110...  Training loss: 1.5257...  5.3126 sec/batch
Epoch: 6/20...  Training Step: 1111...  Training loss: 1.5376...  4.6980 sec/batch
Epoch: 6/20...  Training Step: 1112...  Training loss: 1.4923...  4.8518 sec/batch
Epoch: 6/20...  Training Step: 1113...  Training loss: 1.4901...  4.8799 sec/batch
Epoc

Epoch: 7/20...  Training Step: 1201...  Training loss: 1.5022...  4.6885 sec/batch
Epoch: 7/20...  Training Step: 1202...  Training loss: 1.5328...  4.9079 sec/batch
Epoch: 7/20...  Training Step: 1203...  Training loss: 1.5022...  4.8354 sec/batch
Epoch: 7/20...  Training Step: 1204...  Training loss: 1.4835...  4.8549 sec/batch
Epoch: 7/20...  Training Step: 1205...  Training loss: 1.5172...  4.9580 sec/batch
Epoch: 7/20...  Training Step: 1206...  Training loss: 1.5450...  4.8704 sec/batch
Epoch: 7/20...  Training Step: 1207...  Training loss: 1.5176...  4.8444 sec/batch
Epoch: 7/20...  Training Step: 1208...  Training loss: 1.5400...  5.2241 sec/batch
Epoch: 7/20...  Training Step: 1209...  Training loss: 1.5028...  6.2205 sec/batch
Epoch: 7/20...  Training Step: 1210...  Training loss: 1.5196...  5.4237 sec/batch
Epoch: 7/20...  Training Step: 1211...  Training loss: 1.5056...  4.9173 sec/batch
Epoch: 7/20...  Training Step: 1212...  Training loss: 1.5131...  5.0376 sec/batch
Epoc

Epoch: 7/20...  Training Step: 1300...  Training loss: 1.4811...  5.0044 sec/batch
Epoch: 7/20...  Training Step: 1301...  Training loss: 1.4830...  4.9286 sec/batch
Epoch: 7/20...  Training Step: 1302...  Training loss: 1.4609...  4.8217 sec/batch
Epoch: 7/20...  Training Step: 1303...  Training loss: 1.4476...  4.9220 sec/batch
Epoch: 7/20...  Training Step: 1304...  Training loss: 1.4384...  4.9114 sec/batch
Epoch: 7/20...  Training Step: 1305...  Training loss: 1.4804...  4.9490 sec/batch
Epoch: 7/20...  Training Step: 1306...  Training loss: 1.4830...  5.1479 sec/batch
Epoch: 7/20...  Training Step: 1307...  Training loss: 1.4731...  6.1572 sec/batch
Epoch: 7/20...  Training Step: 1308...  Training loss: 1.4658...  5.6210 sec/batch
Epoch: 7/20...  Training Step: 1309...  Training loss: 1.4771...  4.7373 sec/batch
Epoch: 7/20...  Training Step: 1310...  Training loss: 1.4425...  4.8434 sec/batch
Epoch: 7/20...  Training Step: 1311...  Training loss: 1.4270...  4.9210 sec/batch
Epoc

Epoch: 8/20...  Training Step: 1399...  Training loss: 1.4538...  4.9205 sec/batch
Epoch: 8/20...  Training Step: 1400...  Training loss: 1.4783...  4.8920 sec/batch
Epoch: 8/20...  Training Step: 1401...  Training loss: 1.4483...  4.7311 sec/batch
Epoch: 8/20...  Training Step: 1402...  Training loss: 1.4442...  4.9714 sec/batch
Epoch: 8/20...  Training Step: 1403...  Training loss: 1.4716...  4.8784 sec/batch
Epoch: 8/20...  Training Step: 1404...  Training loss: 1.4872...  4.9196 sec/batch
Epoch: 8/20...  Training Step: 1405...  Training loss: 1.4669...  4.8773 sec/batch
Epoch: 8/20...  Training Step: 1406...  Training loss: 1.4825...  5.4396 sec/batch
Epoch: 8/20...  Training Step: 1407...  Training loss: 1.4550...  6.5047 sec/batch
Epoch: 8/20...  Training Step: 1408...  Training loss: 1.4658...  5.1717 sec/batch
Epoch: 8/20...  Training Step: 1409...  Training loss: 1.4530...  4.8463 sec/batch
Epoch: 8/20...  Training Step: 1410...  Training loss: 1.4671...  4.8642 sec/batch
Epoc

Epoch: 8/20...  Training Step: 1498...  Training loss: 1.4299...  4.2532 sec/batch
Epoch: 8/20...  Training Step: 1499...  Training loss: 1.4278...  5.2996 sec/batch
Epoch: 8/20...  Training Step: 1500...  Training loss: 1.4231...  5.0155 sec/batch
Epoch: 8/20...  Training Step: 1501...  Training loss: 1.3968...  5.1349 sec/batch
Epoch: 8/20...  Training Step: 1502...  Training loss: 1.3962...  4.8249 sec/batch
Epoch: 8/20...  Training Step: 1503...  Training loss: 1.4268...  4.3447 sec/batch
Epoch: 8/20...  Training Step: 1504...  Training loss: 1.4166...  4.1768 sec/batch
Epoch: 8/20...  Training Step: 1505...  Training loss: 1.4209...  4.1985 sec/batch
Epoch: 8/20...  Training Step: 1506...  Training loss: 1.4243...  4.3578 sec/batch
Epoch: 8/20...  Training Step: 1507...  Training loss: 1.4227...  4.3242 sec/batch
Epoch: 8/20...  Training Step: 1508...  Training loss: 1.3755...  4.0280 sec/batch
Epoch: 8/20...  Training Step: 1509...  Training loss: 1.3728...  3.9794 sec/batch
Epoc

Epoch: 9/20...  Training Step: 1597...  Training loss: 1.4094...  4.3580 sec/batch
Epoch: 9/20...  Training Step: 1598...  Training loss: 1.4355...  4.8145 sec/batch
Epoch: 9/20...  Training Step: 1599...  Training loss: 1.4008...  4.4911 sec/batch
Epoch: 9/20...  Training Step: 1600...  Training loss: 1.3844...  4.0798 sec/batch
Epoch: 9/20...  Training Step: 1601...  Training loss: 1.4249...  4.3210 sec/batch
Epoch: 9/20...  Training Step: 1602...  Training loss: 1.4309...  4.0834 sec/batch
Epoch: 9/20...  Training Step: 1603...  Training loss: 1.4058...  3.9186 sec/batch
Epoch: 9/20...  Training Step: 1604...  Training loss: 1.4340...  4.1910 sec/batch
Epoch: 9/20...  Training Step: 1605...  Training loss: 1.4036...  4.3732 sec/batch
Epoch: 9/20...  Training Step: 1606...  Training loss: 1.4136...  4.3668 sec/batch
Epoch: 9/20...  Training Step: 1607...  Training loss: 1.4034...  4.2493 sec/batch
Epoch: 9/20...  Training Step: 1608...  Training loss: 1.4194...  4.0716 sec/batch
Epoc

Epoch: 9/20...  Training Step: 1696...  Training loss: 1.3846...  3.6641 sec/batch
Epoch: 9/20...  Training Step: 1697...  Training loss: 1.3929...  3.6406 sec/batch
Epoch: 9/20...  Training Step: 1698...  Training loss: 1.3865...  3.6996 sec/batch
Epoch: 9/20...  Training Step: 1699...  Training loss: 1.3572...  3.6477 sec/batch
Epoch: 9/20...  Training Step: 1700...  Training loss: 1.3522...  3.6790 sec/batch
Epoch: 9/20...  Training Step: 1701...  Training loss: 1.3861...  3.6680 sec/batch
Epoch: 9/20...  Training Step: 1702...  Training loss: 1.3936...  3.6762 sec/batch
Epoch: 9/20...  Training Step: 1703...  Training loss: 1.3839...  3.6293 sec/batch
Epoch: 9/20...  Training Step: 1704...  Training loss: 1.3869...  3.7464 sec/batch
Epoch: 9/20...  Training Step: 1705...  Training loss: 1.3892...  3.6149 sec/batch
Epoch: 9/20...  Training Step: 1706...  Training loss: 1.3446...  3.6751 sec/batch
Epoch: 9/20...  Training Step: 1707...  Training loss: 1.3345...  3.8666 sec/batch
Epoc

Epoch: 10/20...  Training Step: 1795...  Training loss: 1.3708...  3.8177 sec/batch
Epoch: 10/20...  Training Step: 1796...  Training loss: 1.3891...  3.7343 sec/batch
Epoch: 10/20...  Training Step: 1797...  Training loss: 1.3573...  3.8228 sec/batch
Epoch: 10/20...  Training Step: 1798...  Training loss: 1.3595...  3.8153 sec/batch
Epoch: 10/20...  Training Step: 1799...  Training loss: 1.3847...  3.7551 sec/batch
Epoch: 10/20...  Training Step: 1800...  Training loss: 1.3854...  3.8157 sec/batch
Epoch: 10/20...  Training Step: 1801...  Training loss: 1.3714...  3.5455 sec/batch
Epoch: 10/20...  Training Step: 1802...  Training loss: 1.3977...  4.1340 sec/batch
Epoch: 10/20...  Training Step: 1803...  Training loss: 1.3622...  3.9292 sec/batch
Epoch: 10/20...  Training Step: 1804...  Training loss: 1.3872...  3.7767 sec/batch
Epoch: 10/20...  Training Step: 1805...  Training loss: 1.3641...  3.8370 sec/batch
Epoch: 10/20...  Training Step: 1806...  Training loss: 1.3715...  3.8253 se

Epoch: 10/20...  Training Step: 1893...  Training loss: 1.3397...  3.8744 sec/batch
Epoch: 10/20...  Training Step: 1894...  Training loss: 1.3595...  4.0069 sec/batch
Epoch: 10/20...  Training Step: 1895...  Training loss: 1.3569...  4.0992 sec/batch
Epoch: 10/20...  Training Step: 1896...  Training loss: 1.3358...  3.8248 sec/batch
Epoch: 10/20...  Training Step: 1897...  Training loss: 1.3227...  3.9430 sec/batch
Epoch: 10/20...  Training Step: 1898...  Training loss: 1.3225...  3.8490 sec/batch
Epoch: 10/20...  Training Step: 1899...  Training loss: 1.3519...  3.8620 sec/batch
Epoch: 10/20...  Training Step: 1900...  Training loss: 1.3563...  4.0370 sec/batch
Epoch: 10/20...  Training Step: 1901...  Training loss: 1.3573...  3.8375 sec/batch
Epoch: 10/20...  Training Step: 1902...  Training loss: 1.3403...  3.8910 sec/batch
Epoch: 10/20...  Training Step: 1903...  Training loss: 1.3509...  3.8701 sec/batch
Epoch: 10/20...  Training Step: 1904...  Training loss: 1.3164...  3.8389 se

Epoch: 11/20...  Training Step: 1991...  Training loss: 1.3444...  4.8630 sec/batch
Epoch: 11/20...  Training Step: 1992...  Training loss: 1.3375...  5.0065 sec/batch
Epoch: 11/20...  Training Step: 1993...  Training loss: 1.3415...  4.8705 sec/batch
Epoch: 11/20...  Training Step: 1994...  Training loss: 1.3682...  4.9442 sec/batch
Epoch: 11/20...  Training Step: 1995...  Training loss: 1.3388...  4.9660 sec/batch
Epoch: 11/20...  Training Step: 1996...  Training loss: 1.3255...  5.1550 sec/batch
Epoch: 11/20...  Training Step: 1997...  Training loss: 1.3612...  4.9473 sec/batch
Epoch: 11/20...  Training Step: 1998...  Training loss: 1.3628...  5.0426 sec/batch
Epoch: 11/20...  Training Step: 1999...  Training loss: 1.3499...  4.9655 sec/batch
Epoch: 11/20...  Training Step: 2000...  Training loss: 1.3691...  4.9735 sec/batch
Epoch: 11/20...  Training Step: 2001...  Training loss: 1.3472...  4.7794 sec/batch
Epoch: 11/20...  Training Step: 2002...  Training loss: 1.3596...  5.1612 se

Epoch: 11/20...  Training Step: 2089...  Training loss: 1.3180...  5.0023 sec/batch
Epoch: 11/20...  Training Step: 2090...  Training loss: 1.3493...  5.1429 sec/batch
Epoch: 11/20...  Training Step: 2091...  Training loss: 1.3095...  5.0138 sec/batch
Epoch: 11/20...  Training Step: 2092...  Training loss: 1.3326...  5.0614 sec/batch
Epoch: 11/20...  Training Step: 2093...  Training loss: 1.3366...  5.0701 sec/batch
Epoch: 11/20...  Training Step: 2094...  Training loss: 1.3209...  5.0001 sec/batch
Epoch: 11/20...  Training Step: 2095...  Training loss: 1.3037...  5.2112 sec/batch
Epoch: 11/20...  Training Step: 2096...  Training loss: 1.2975...  5.1682 sec/batch
Epoch: 11/20...  Training Step: 2097...  Training loss: 1.3311...  5.3493 sec/batch
Epoch: 11/20...  Training Step: 2098...  Training loss: 1.3355...  5.1949 sec/batch
Epoch: 11/20...  Training Step: 2099...  Training loss: 1.3251...  5.0831 sec/batch
Epoch: 11/20...  Training Step: 2100...  Training loss: 1.3288...  4.9832 se

Epoch: 12/20...  Training Step: 2187...  Training loss: 1.3465...  5.0555 sec/batch
Epoch: 12/20...  Training Step: 2188...  Training loss: 1.3351...  5.0983 sec/batch
Epoch: 12/20...  Training Step: 2189...  Training loss: 1.3163...  5.1429 sec/batch
Epoch: 12/20...  Training Step: 2190...  Training loss: 1.3193...  5.0881 sec/batch
Epoch: 12/20...  Training Step: 2191...  Training loss: 1.3248...  5.1559 sec/batch
Epoch: 12/20...  Training Step: 2192...  Training loss: 1.3411...  5.0742 sec/batch
Epoch: 12/20...  Training Step: 2193...  Training loss: 1.3160...  5.4844 sec/batch
Epoch: 12/20...  Training Step: 2194...  Training loss: 1.3101...  5.3699 sec/batch
Epoch: 12/20...  Training Step: 2195...  Training loss: 1.3418...  5.3763 sec/batch
Epoch: 12/20...  Training Step: 2196...  Training loss: 1.3411...  5.3503 sec/batch
Epoch: 12/20...  Training Step: 2197...  Training loss: 1.3284...  5.4656 sec/batch
Epoch: 12/20...  Training Step: 2198...  Training loss: 1.3510...  5.4312 se

Epoch: 12/20...  Training Step: 2285...  Training loss: 1.3219...  5.0623 sec/batch
Epoch: 12/20...  Training Step: 2286...  Training loss: 1.3127...  5.0312 sec/batch
Epoch: 12/20...  Training Step: 2287...  Training loss: 1.2945...  5.1485 sec/batch
Epoch: 12/20...  Training Step: 2288...  Training loss: 1.3322...  5.1699 sec/batch
Epoch: 12/20...  Training Step: 2289...  Training loss: 1.2863...  4.9918 sec/batch
Epoch: 12/20...  Training Step: 2290...  Training loss: 1.3152...  5.0853 sec/batch
Epoch: 12/20...  Training Step: 2291...  Training loss: 1.3165...  5.1678 sec/batch
Epoch: 12/20...  Training Step: 2292...  Training loss: 1.3002...  4.9981 sec/batch
Epoch: 12/20...  Training Step: 2293...  Training loss: 1.2816...  5.1133 sec/batch
Epoch: 12/20...  Training Step: 2294...  Training loss: 1.2762...  5.0244 sec/batch
Epoch: 12/20...  Training Step: 2295...  Training loss: 1.3042...  5.6089 sec/batch
Epoch: 12/20...  Training Step: 2296...  Training loss: 1.3126...  6.5474 se

Epoch: 13/20...  Training Step: 2383...  Training loss: 1.2966...  4.6772 sec/batch
Epoch: 13/20...  Training Step: 2384...  Training loss: 1.2996...  4.2130 sec/batch
Epoch: 13/20...  Training Step: 2385...  Training loss: 1.3097...  3.9690 sec/batch
Epoch: 13/20...  Training Step: 2386...  Training loss: 1.2963...  4.2486 sec/batch
Epoch: 13/20...  Training Step: 2387...  Training loss: 1.2793...  4.4200 sec/batch
Epoch: 13/20...  Training Step: 2388...  Training loss: 1.2957...  4.5907 sec/batch
Epoch: 13/20...  Training Step: 2389...  Training loss: 1.2949...  4.2385 sec/batch
Epoch: 13/20...  Training Step: 2390...  Training loss: 1.3138...  4.2306 sec/batch
Epoch: 13/20...  Training Step: 2391...  Training loss: 1.2864...  4.8271 sec/batch
Epoch: 13/20...  Training Step: 2392...  Training loss: 1.2807...  4.3361 sec/batch
Epoch: 13/20...  Training Step: 2393...  Training loss: 1.3134...  4.5142 sec/batch
Epoch: 13/20...  Training Step: 2394...  Training loss: 1.3161...  4.3795 se

Epoch: 13/20...  Training Step: 2481...  Training loss: 1.2810...  4.1818 sec/batch
Epoch: 13/20...  Training Step: 2482...  Training loss: 1.2919...  4.8189 sec/batch
Epoch: 13/20...  Training Step: 2483...  Training loss: 1.2921...  4.9105 sec/batch
Epoch: 13/20...  Training Step: 2484...  Training loss: 1.2918...  4.9581 sec/batch
Epoch: 13/20...  Training Step: 2485...  Training loss: 1.2768...  4.5255 sec/batch
Epoch: 13/20...  Training Step: 2486...  Training loss: 1.3146...  4.1931 sec/batch
Epoch: 13/20...  Training Step: 2487...  Training loss: 1.2688...  4.1822 sec/batch
Epoch: 13/20...  Training Step: 2488...  Training loss: 1.3017...  4.6974 sec/batch
Epoch: 13/20...  Training Step: 2489...  Training loss: 1.2914...  4.2629 sec/batch
Epoch: 13/20...  Training Step: 2490...  Training loss: 1.2849...  4.0813 sec/batch
Epoch: 13/20...  Training Step: 2491...  Training loss: 1.2619...  4.1636 sec/batch
Epoch: 13/20...  Training Step: 2492...  Training loss: 1.2574...  4.2310 se

Epoch: 14/20...  Training Step: 2579...  Training loss: 1.2703...  4.3790 sec/batch
Epoch: 14/20...  Training Step: 2580...  Training loss: 1.2526...  4.2982 sec/batch
Epoch: 14/20...  Training Step: 2581...  Training loss: 1.2873...  4.3245 sec/batch
Epoch: 14/20...  Training Step: 2582...  Training loss: 1.2804...  4.4044 sec/batch
Epoch: 14/20...  Training Step: 2583...  Training loss: 1.2933...  4.3798 sec/batch
Epoch: 14/20...  Training Step: 2584...  Training loss: 1.2865...  4.4111 sec/batch
Epoch: 14/20...  Training Step: 2585...  Training loss: 1.2730...  4.4320 sec/batch
Epoch: 14/20...  Training Step: 2586...  Training loss: 1.2805...  4.4210 sec/batch
Epoch: 14/20...  Training Step: 2587...  Training loss: 1.2867...  4.6465 sec/batch
Epoch: 14/20...  Training Step: 2588...  Training loss: 1.3058...  4.4062 sec/batch
Epoch: 14/20...  Training Step: 2589...  Training loss: 1.2644...  4.4134 sec/batch
Epoch: 14/20...  Training Step: 2590...  Training loss: 1.2414...  4.4708 se

Epoch: 14/20...  Training Step: 2677...  Training loss: 1.2735...  5.1423 sec/batch
Epoch: 14/20...  Training Step: 2678...  Training loss: 1.2707...  4.8115 sec/batch
Epoch: 14/20...  Training Step: 2679...  Training loss: 1.2627...  4.6128 sec/batch
Epoch: 14/20...  Training Step: 2680...  Training loss: 1.2680...  4.6030 sec/batch
Epoch: 14/20...  Training Step: 2681...  Training loss: 1.2784...  4.6418 sec/batch
Epoch: 14/20...  Training Step: 2682...  Training loss: 1.2803...  4.5403 sec/batch
Epoch: 14/20...  Training Step: 2683...  Training loss: 1.2611...  4.6272 sec/batch
Epoch: 14/20...  Training Step: 2684...  Training loss: 1.2794...  4.7297 sec/batch
Epoch: 14/20...  Training Step: 2685...  Training loss: 1.2615...  4.5828 sec/batch
Epoch: 14/20...  Training Step: 2686...  Training loss: 1.2754...  4.4586 sec/batch
Epoch: 14/20...  Training Step: 2687...  Training loss: 1.2773...  4.5816 sec/batch
Epoch: 14/20...  Training Step: 2688...  Training loss: 1.2599...  4.7032 se

Epoch: 15/20...  Training Step: 2775...  Training loss: 1.2617...  4.6325 sec/batch
Epoch: 15/20...  Training Step: 2776...  Training loss: 1.2970...  4.6224 sec/batch
Epoch: 15/20...  Training Step: 2777...  Training loss: 1.2390...  4.5978 sec/batch
Epoch: 15/20...  Training Step: 2778...  Training loss: 1.2255...  4.9031 sec/batch
Epoch: 15/20...  Training Step: 2779...  Training loss: 1.2744...  4.9563 sec/batch
Epoch: 15/20...  Training Step: 2780...  Training loss: 1.2657...  4.7411 sec/batch
Epoch: 15/20...  Training Step: 2781...  Training loss: 1.2730...  4.7612 sec/batch
Epoch: 15/20...  Training Step: 2782...  Training loss: 1.2725...  4.6369 sec/batch
Epoch: 15/20...  Training Step: 2783...  Training loss: 1.2554...  4.7653 sec/batch
Epoch: 15/20...  Training Step: 2784...  Training loss: 1.2634...  4.6111 sec/batch
Epoch: 15/20...  Training Step: 2785...  Training loss: 1.2712...  4.6055 sec/batch
Epoch: 15/20...  Training Step: 2786...  Training loss: 1.2790...  4.6395 se

Epoch: 15/20...  Training Step: 2873...  Training loss: 1.2674...  3.5933 sec/batch
Epoch: 15/20...  Training Step: 2874...  Training loss: 1.2558...  3.5850 sec/batch
Epoch: 15/20...  Training Step: 2875...  Training loss: 1.2699...  3.5810 sec/batch
Epoch: 15/20...  Training Step: 2876...  Training loss: 1.2681...  3.5663 sec/batch
Epoch: 15/20...  Training Step: 2877...  Training loss: 1.2548...  3.5676 sec/batch
Epoch: 15/20...  Training Step: 2878...  Training loss: 1.2504...  3.5427 sec/batch
Epoch: 15/20...  Training Step: 2879...  Training loss: 1.2718...  3.5795 sec/batch
Epoch: 15/20...  Training Step: 2880...  Training loss: 1.2700...  3.6030 sec/batch
Epoch: 15/20...  Training Step: 2881...  Training loss: 1.2470...  3.5992 sec/batch
Epoch: 15/20...  Training Step: 2882...  Training loss: 1.2791...  3.8672 sec/batch
Epoch: 15/20...  Training Step: 2883...  Training loss: 1.2526...  3.7612 sec/batch
Epoch: 15/20...  Training Step: 2884...  Training loss: 1.2608...  3.6071 se

Epoch: 16/20...  Training Step: 2971...  Training loss: 1.3828...  3.9257 sec/batch
Epoch: 16/20...  Training Step: 2972...  Training loss: 1.2721...  4.0191 sec/batch
Epoch: 16/20...  Training Step: 2973...  Training loss: 1.2575...  3.9927 sec/batch
Epoch: 16/20...  Training Step: 2974...  Training loss: 1.2830...  4.0832 sec/batch
Epoch: 16/20...  Training Step: 2975...  Training loss: 1.2430...  4.0627 sec/batch
Epoch: 16/20...  Training Step: 2976...  Training loss: 1.2128...  4.2793 sec/batch
Epoch: 16/20...  Training Step: 2977...  Training loss: 1.2493...  4.1093 sec/batch
Epoch: 16/20...  Training Step: 2978...  Training loss: 1.2519...  4.0370 sec/batch
Epoch: 16/20...  Training Step: 2979...  Training loss: 1.2531...  4.1174 sec/batch
Epoch: 16/20...  Training Step: 2980...  Training loss: 1.2498...  3.9992 sec/batch
Epoch: 16/20...  Training Step: 2981...  Training loss: 1.2339...  4.0923 sec/batch
Epoch: 16/20...  Training Step: 2982...  Training loss: 1.2496...  3.9651 se

Epoch: 16/20...  Training Step: 3069...  Training loss: 1.2377...  4.0892 sec/batch
Epoch: 16/20...  Training Step: 3070...  Training loss: 1.2238...  4.1187 sec/batch
Epoch: 16/20...  Training Step: 3071...  Training loss: 1.2490...  4.1556 sec/batch
Epoch: 16/20...  Training Step: 3072...  Training loss: 1.2442...  4.2034 sec/batch
Epoch: 16/20...  Training Step: 3073...  Training loss: 1.2555...  4.1013 sec/batch
Epoch: 16/20...  Training Step: 3074...  Training loss: 1.2424...  4.1853 sec/batch
Epoch: 16/20...  Training Step: 3075...  Training loss: 1.2407...  4.1614 sec/batch
Epoch: 16/20...  Training Step: 3076...  Training loss: 1.2330...  4.1536 sec/batch
Epoch: 16/20...  Training Step: 3077...  Training loss: 1.2545...  4.3922 sec/batch
Epoch: 16/20...  Training Step: 3078...  Training loss: 1.2613...  4.1986 sec/batch
Epoch: 16/20...  Training Step: 3079...  Training loss: 1.2370...  4.0825 sec/batch
Epoch: 16/20...  Training Step: 3080...  Training loss: 1.2660...  4.1691 se

Epoch: 16/20...  Training Step: 3167...  Training loss: 1.2374...  4.1897 sec/batch
Epoch: 16/20...  Training Step: 3168...  Training loss: 1.2399...  4.1377 sec/batch
Epoch: 17/20...  Training Step: 3169...  Training loss: 1.3587...  4.4016 sec/batch
Epoch: 17/20...  Training Step: 3170...  Training loss: 1.2603...  4.1211 sec/batch
Epoch: 17/20...  Training Step: 3171...  Training loss: 1.2477...  4.1301 sec/batch
Epoch: 17/20...  Training Step: 3172...  Training loss: 1.2671...  4.1940 sec/batch
Epoch: 17/20...  Training Step: 3173...  Training loss: 1.2272...  4.1563 sec/batch
Epoch: 17/20...  Training Step: 3174...  Training loss: 1.2106...  4.2645 sec/batch
Epoch: 17/20...  Training Step: 3175...  Training loss: 1.2452...  4.2021 sec/batch
Epoch: 17/20...  Training Step: 3176...  Training loss: 1.2409...  4.4498 sec/batch
Epoch: 17/20...  Training Step: 3177...  Training loss: 1.2519...  4.1298 sec/batch
Epoch: 17/20...  Training Step: 3178...  Training loss: 1.2495...  4.1258 se

Epoch: 17/20...  Training Step: 3265...  Training loss: 1.2494...  4.2883 sec/batch
Epoch: 17/20...  Training Step: 3266...  Training loss: 1.2062...  4.1114 sec/batch
Epoch: 17/20...  Training Step: 3267...  Training loss: 1.2162...  4.1305 sec/batch
Epoch: 17/20...  Training Step: 3268...  Training loss: 1.2215...  4.2038 sec/batch
Epoch: 17/20...  Training Step: 3269...  Training loss: 1.2374...  4.1747 sec/batch
Epoch: 17/20...  Training Step: 3270...  Training loss: 1.2220...  4.0821 sec/batch
Epoch: 17/20...  Training Step: 3271...  Training loss: 1.2432...  4.2084 sec/batch
Epoch: 17/20...  Training Step: 3272...  Training loss: 1.2278...  4.1341 sec/batch
Epoch: 17/20...  Training Step: 3273...  Training loss: 1.2290...  4.1681 sec/batch
Epoch: 17/20...  Training Step: 3274...  Training loss: 1.2309...  4.2458 sec/batch
Epoch: 17/20...  Training Step: 3275...  Training loss: 1.2412...  4.5311 sec/batch
Epoch: 17/20...  Training Step: 3276...  Training loss: 1.2434...  4.2448 se

Epoch: 17/20...  Training Step: 3363...  Training loss: 1.2015...  4.2163 sec/batch
Epoch: 17/20...  Training Step: 3364...  Training loss: 1.2385...  4.1636 sec/batch
Epoch: 17/20...  Training Step: 3365...  Training loss: 1.2321...  4.2041 sec/batch
Epoch: 17/20...  Training Step: 3366...  Training loss: 1.2280...  4.2206 sec/batch
Epoch: 18/20...  Training Step: 3367...  Training loss: 1.3532...  4.1774 sec/batch
Epoch: 18/20...  Training Step: 3368...  Training loss: 1.2451...  4.1677 sec/batch
Epoch: 18/20...  Training Step: 3369...  Training loss: 1.2342...  4.2623 sec/batch
Epoch: 18/20...  Training Step: 3370...  Training loss: 1.2547...  4.2114 sec/batch
Epoch: 18/20...  Training Step: 3371...  Training loss: 1.2138...  4.1922 sec/batch
Epoch: 18/20...  Training Step: 3372...  Training loss: 1.2019...  4.3018 sec/batch
Epoch: 18/20...  Training Step: 3373...  Training loss: 1.2292...  4.2299 sec/batch
Epoch: 18/20...  Training Step: 3374...  Training loss: 1.2283...  4.4603 se

Epoch: 18/20...  Training Step: 3461...  Training loss: 1.2148...  4.2001 sec/batch
Epoch: 18/20...  Training Step: 3462...  Training loss: 1.2433...  4.2003 sec/batch
Epoch: 18/20...  Training Step: 3463...  Training loss: 1.2405...  4.2116 sec/batch
Epoch: 18/20...  Training Step: 3464...  Training loss: 1.1919...  4.2258 sec/batch
Epoch: 18/20...  Training Step: 3465...  Training loss: 1.2109...  4.2494 sec/batch
Epoch: 18/20...  Training Step: 3466...  Training loss: 1.2065...  4.2335 sec/batch
Epoch: 18/20...  Training Step: 3467...  Training loss: 1.2271...  4.2511 sec/batch
Epoch: 18/20...  Training Step: 3468...  Training loss: 1.2090...  4.1747 sec/batch
Epoch: 18/20...  Training Step: 3469...  Training loss: 1.2239...  4.2269 sec/batch
Epoch: 18/20...  Training Step: 3470...  Training loss: 1.2152...  4.2006 sec/batch
Epoch: 18/20...  Training Step: 3471...  Training loss: 1.2187...  4.2271 sec/batch
Epoch: 18/20...  Training Step: 3472...  Training loss: 1.2166...  4.4195 se

Epoch: 18/20...  Training Step: 3559...  Training loss: 1.2263...  5.3296 sec/batch
Epoch: 18/20...  Training Step: 3560...  Training loss: 1.2155...  5.4111 sec/batch
Epoch: 18/20...  Training Step: 3561...  Training loss: 1.1828...  5.3662 sec/batch
Epoch: 18/20...  Training Step: 3562...  Training loss: 1.2330...  5.9744 sec/batch
Epoch: 18/20...  Training Step: 3563...  Training loss: 1.2217...  5.8431 sec/batch
Epoch: 18/20...  Training Step: 3564...  Training loss: 1.2073...  5.8433 sec/batch
Epoch: 19/20...  Training Step: 3565...  Training loss: 1.3389...  5.7851 sec/batch
Epoch: 19/20...  Training Step: 3566...  Training loss: 1.2336...  5.7826 sec/batch
Epoch: 19/20...  Training Step: 3567...  Training loss: 1.2230...  5.9561 sec/batch
Epoch: 19/20...  Training Step: 3568...  Training loss: 1.2499...  5.9723 sec/batch
Epoch: 19/20...  Training Step: 3569...  Training loss: 1.2056...  5.7483 sec/batch
Epoch: 19/20...  Training Step: 3570...  Training loss: 1.1911...  5.6776 se

Epoch: 19/20...  Training Step: 3657...  Training loss: 1.1951...  4.3458 sec/batch
Epoch: 19/20...  Training Step: 3658...  Training loss: 1.1878...  4.1637 sec/batch
Epoch: 19/20...  Training Step: 3659...  Training loss: 1.2152...  4.2682 sec/batch
Epoch: 19/20...  Training Step: 3660...  Training loss: 1.2271...  4.2721 sec/batch
Epoch: 19/20...  Training Step: 3661...  Training loss: 1.2232...  4.1922 sec/batch
Epoch: 19/20...  Training Step: 3662...  Training loss: 1.1873...  4.1233 sec/batch
Epoch: 19/20...  Training Step: 3663...  Training loss: 1.1970...  4.1878 sec/batch
Epoch: 19/20...  Training Step: 3664...  Training loss: 1.1999...  4.2307 sec/batch
Epoch: 19/20...  Training Step: 3665...  Training loss: 1.2181...  4.1946 sec/batch
Epoch: 19/20...  Training Step: 3666...  Training loss: 1.2133...  4.1512 sec/batch
Epoch: 19/20...  Training Step: 3667...  Training loss: 1.2241...  4.2298 sec/batch
Epoch: 19/20...  Training Step: 3668...  Training loss: 1.2022...  4.2724 se

Epoch: 19/20...  Training Step: 3755...  Training loss: 1.1879...  4.3237 sec/batch
Epoch: 19/20...  Training Step: 3756...  Training loss: 1.2023...  4.1874 sec/batch
Epoch: 19/20...  Training Step: 3757...  Training loss: 1.2179...  4.2415 sec/batch
Epoch: 19/20...  Training Step: 3758...  Training loss: 1.2070...  4.2441 sec/batch
Epoch: 19/20...  Training Step: 3759...  Training loss: 1.1807...  4.2141 sec/batch
Epoch: 19/20...  Training Step: 3760...  Training loss: 1.2124...  4.2612 sec/batch
Epoch: 19/20...  Training Step: 3761...  Training loss: 1.1989...  4.2209 sec/batch
Epoch: 19/20...  Training Step: 3762...  Training loss: 1.2070...  4.2540 sec/batch
Epoch: 20/20...  Training Step: 3763...  Training loss: 1.3449...  4.2225 sec/batch
Epoch: 20/20...  Training Step: 3764...  Training loss: 1.2162...  4.2429 sec/batch
Epoch: 20/20...  Training Step: 3765...  Training loss: 1.2060...  4.2799 sec/batch
Epoch: 20/20...  Training Step: 3766...  Training loss: 1.2300...  4.2280 se

Epoch: 20/20...  Training Step: 3853...  Training loss: 1.1897...  4.2017 sec/batch
Epoch: 20/20...  Training Step: 3854...  Training loss: 1.1988...  4.2014 sec/batch
Epoch: 20/20...  Training Step: 3855...  Training loss: 1.1869...  4.1880 sec/batch
Epoch: 20/20...  Training Step: 3856...  Training loss: 1.1865...  4.2588 sec/batch
Epoch: 20/20...  Training Step: 3857...  Training loss: 1.2011...  4.2666 sec/batch
Epoch: 20/20...  Training Step: 3858...  Training loss: 1.2169...  4.2671 sec/batch
Epoch: 20/20...  Training Step: 3859...  Training loss: 1.2189...  4.6276 sec/batch
Epoch: 20/20...  Training Step: 3860...  Training loss: 1.1763...  6.0013 sec/batch
Epoch: 20/20...  Training Step: 3861...  Training loss: 1.1962...  5.7362 sec/batch
Epoch: 20/20...  Training Step: 3862...  Training loss: 1.1917...  5.7360 sec/batch
Epoch: 20/20...  Training Step: 3863...  Training loss: 1.2131...  5.7321 sec/batch
Epoch: 20/20...  Training Step: 3864...  Training loss: 1.2019...  5.5880 se

Epoch: 20/20...  Training Step: 3951...  Training loss: 1.2072...  5.4975 sec/batch
Epoch: 20/20...  Training Step: 3952...  Training loss: 1.2066...  5.5876 sec/batch
Epoch: 20/20...  Training Step: 3953...  Training loss: 1.1814...  5.4422 sec/batch
Epoch: 20/20...  Training Step: 3954...  Training loss: 1.1930...  5.4803 sec/batch
Epoch: 20/20...  Training Step: 3955...  Training loss: 1.2115...  5.4946 sec/batch
Epoch: 20/20...  Training Step: 3956...  Training loss: 1.1952...  5.9770 sec/batch
Epoch: 20/20...  Training Step: 3957...  Training loss: 1.1753...  5.5151 sec/batch
Epoch: 20/20...  Training Step: 3958...  Training loss: 1.2092...  5.4895 sec/batch
Epoch: 20/20...  Training Step: 3959...  Training loss: 1.2010...  5.4968 sec/batch
Epoch: 20/20...  Training Step: 3960...  Training loss: 1.1969...  5.4167 sec/batch


#### Saved checkpoints

Read up on saving and loading checkpoints here: https://www.tensorflow.org/programmers_guide/variables

In [18]:
tf.train.get_checkpoint_state('checkpoints')

model_checkpoint_path: "checkpoints/i3960_l512.ckpt"
all_model_checkpoint_paths: "checkpoints/i200_l512.ckpt"
all_model_checkpoint_paths: "checkpoints/i400_l512.ckpt"
all_model_checkpoint_paths: "checkpoints/i600_l512.ckpt"
all_model_checkpoint_paths: "checkpoints/i800_l512.ckpt"
all_model_checkpoint_paths: "checkpoints/i1000_l512.ckpt"
all_model_checkpoint_paths: "checkpoints/i1200_l512.ckpt"
all_model_checkpoint_paths: "checkpoints/i1400_l512.ckpt"
all_model_checkpoint_paths: "checkpoints/i1600_l512.ckpt"
all_model_checkpoint_paths: "checkpoints/i1800_l512.ckpt"
all_model_checkpoint_paths: "checkpoints/i2000_l512.ckpt"
all_model_checkpoint_paths: "checkpoints/i2200_l512.ckpt"
all_model_checkpoint_paths: "checkpoints/i2400_l512.ckpt"
all_model_checkpoint_paths: "checkpoints/i2600_l512.ckpt"
all_model_checkpoint_paths: "checkpoints/i2800_l512.ckpt"
all_model_checkpoint_paths: "checkpoints/i3000_l512.ckpt"
all_model_checkpoint_paths: "checkpoints/i3200_l512.ckpt"
all_model_checkpoint_pa

## Sampling

Now that the network is trained, we'll can use it to generate new text. The idea is that we pass in a character, then the network will predict the next character. We can use the new one, to predict the next one. And we keep doing this to generate all new text. I also included some functionality to prime the network with some text by passing in a string and building up a state from that.

The network gives us predictions for each character. To reduce noise and make things a little less random, I'm going to only choose a new character from the top N most likely characters.



In [19]:
def pick_top_n(preds, vocab_size, top_n=5):
    p = np.squeeze(preds)
    p[np.argsort(p)[:-top_n]] = 0
    p = p / np.sum(p)
    c = np.random.choice(vocab_size, 1, p=p)[0]
    return c

In [20]:
def sample(checkpoint, n_samples, lstm_size, vocab_size, prime="The "):
    samples = [c for c in prime]
    model = CharRNN(len(vocab), lstm_size=lstm_size, sampling=True)
    saver = tf.train.Saver()
    with tf.Session() as sess:
        saver.restore(sess, checkpoint)
        new_state = sess.run(model.initial_state)
        for c in prime:
            x = np.zeros((1, 1))
            x[0,0] = vocab_to_int[c]
            feed = {model.inputs: x,
                    model.keep_prob: 1.,
                    model.initial_state: new_state}
            preds, new_state = sess.run([model.prediction, model.final_state], 
                                         feed_dict=feed)

        c = pick_top_n(preds, len(vocab))
        samples.append(int_to_vocab[c])

        for i in range(n_samples):
            x[0,0] = c
            feed = {model.inputs: x,
                    model.keep_prob: 1.,
                    model.initial_state: new_state}
            preds, new_state = sess.run([model.prediction, model.final_state], 
                                         feed_dict=feed)

            c = pick_top_n(preds, len(vocab))
            samples.append(int_to_vocab[c])
        
    return ''.join(samples)

Here, pass in the path to a checkpoint and sample from the network.

In [21]:
tf.train.latest_checkpoint('checkpoints')

'checkpoints/i3960_l512.ckpt'

In [22]:
checkpoint = tf.train.latest_checkpoint('checkpoints')
samp = sample(checkpoint, 2000, lstm_size, len(vocab), prime="Far")
print(samp)

INFO:tensorflow:Restoring parameters from checkpoints/i3960_l512.ckpt
Farlon.
"What did you care for her here!" said Levin, smiling,
as though a sort of talk of companion, all the mother was. "What are
you changed? I don't want to go and district what they have never
cared for me."

"What is it it?" said Levin, and took the same time at three, and while
all the peasant he could have to be any one of a personal still. The
strength he defined that was stoping; there was no married would him
that he comes about that the merchant, and she fancied. And that which
he did not ask her heart. They should have started.

"If it has been done, and I can't have been more and she was standing
at their construct and a silly signiforable family," said Levin.

"Well, what is that they don't look at the coming to a chair, to
speak, a lovely means to the brother."

"Yes, I can't tell you what you do not agree to hear home whether I had
as he did not listen to you," he, and that what he was to see that he

In [23]:
checkpoint = 'checkpoints/i200_l512.ckpt'
samp = sample(checkpoint, 1000, lstm_size, len(vocab), prime="Far")
print(samp)

INFO:tensorflow:Restoring parameters from checkpoints/i200_l512.ckpt
Farly of or on to ton tar ant ho win her and
the wal ses talin sas ifith, and he has he sing tha he als
the there sere the to le har the had he tard soth ho seras to shes sil sit se whar he sed as the her the tand.


Anth has sand this her, the will sin or af sat tere, and the the ad on tal the thes, ho the
houd th welse the tate he sest an hes sores at ato so he sist and one his hit thou led, hate and this ther, the sot ha hed tastite, sout ha he war se tise on woun he so too the would hos wal at he theres.
.
"Whe s anthe se te weshe to sote thes te the he wore the the he hor withe,, and sh tine he
the asd sonte ander sot on he wher sher, had he the withe who he selind, and at arithe has and thin ho sons and af tathe th he than sore wot his the hin the hese sut serend the hed sothite hou shor the sore and thint
touth ale and al wom th he ware sou sat of ald the thes and of sheter the sous he sesting.

Anler tith he
t

In [24]:
checkpoint = 'checkpoints/i600_l512.ckpt'
samp = sample(checkpoint, 1000, lstm_size, len(vocab), prime="Far")
print(samp)

INFO:tensorflow:Restoring parameters from checkpoints/i600_l512.ckpt
Farnd of his with astitaly and
the soncions and the went him heard a supporstion. He wantation to the coured thome her and and the soretely. His seeted
trinked had her some an aster that heart, and with his and her said
to the
pristian of consension, to that the sond to the potially with her. He said. There was hownerss was and the seid to she head so steplady ont a porition.

"At a man and had seened the provisce and as and with her ass and sout to be and sat as
the sert was his forthing of
chillece was to the sare a sore there of her his suntente of anstand his seed the moss he
tooking the momen and steriding oncorace that
the dossion.


"What say in so had stere to her, the sould be doning had to a prospensing. The
restoun of that
is said the was on the mustion of see he he had both her
andered his frandse that haven to this the hads of the pointion tak at a chertors, at a mestion out the
carrous, betound to his se

In [25]:
checkpoint = 'checkpoints/i1200_l512.ckpt'
samp = sample(checkpoint, 1000, lstm_size, len(vocab), prime="Far")
print(samp)

INFO:tensorflow:Restoring parameters from checkpoints/i1200_l512.ckpt
Farting on that that impordance. And he said his hands, trouble
there was something and the tarking.
"If he said ten itsor and so that I ampering about the same at their confire the courting. The carriage with her and think of the presson, and what had so more there without hand, and they asked in in a man, while he was a might be
taken to her horses," he said,
"at the done, and she challed thought to the postible of
all this are to him. And I could never hers that's see in an end an one,"
he said, which always
were since that she was not to see her to all the person to herself how that they saw that time shouted to have
here of her form their camply by his water of the stords would sake the
talling of the stirl shame were tronging out at one of their hand. The contrameming, with she consested his he felt it.

"There's nothen," asseen Vronsky, but he sood her fine the calliagine had brother and same, and the
she had 