In [2]:
import numpy as np

In [6]:
#declare a scalar 

scalar1 = np.array(5)

print(scalar1)


5


In [7]:
print(scalar1.shape)

()


In [8]:
scalar1+5


10

In [9]:
vector1 = np.array([1,2,3])

print(vector1)

[1 2 3]


In [10]:
vector1.shape

(3,)

In [12]:
vector1[1:]

array([2, 3])

In [15]:
m = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [16]:
m.shape

(3, 3)

In [23]:
v = np.array([1,2,3,4])
x = v.reshape(1,4)

In [24]:
x

array([[1, 2, 3, 4]])

In [27]:
x = v[:,None]
x

array([[1],
       [2],
       [3],
       [4]])

In [28]:
v + 5

array([6, 7, 8, 9])

In [29]:
v*2

array([2, 4, 6, 8])

In [30]:
n =  m*2
n

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [31]:
m*n

array([[  2,   8,  18],
       [ 32,  50,  72],
       [ 98, 128, 162]])

In [49]:
v2 = np.array([3,4,5,4,6,8])

v3 = v2.reshape(3,2)

c = np.matmul(m,v3)
print(v2)
print(v3)
print(c)

[3 4 5 4 6 8]
[[3 4]
 [5 4]
 [6 8]]
[[ 31  36]
 [ 73  84]
 [115 132]]


In [50]:
v3 = v2.reshape(3,1,2)

In [51]:
v3

array([[[3, 4]],

       [[5, 4]],

       [[6, 8]]])

In [53]:
v3.shape

(3, 1, 2)

In [3]:
inputs =[1,2,7]

a = np.array(inputs)

a

array([1, 2, 7])

In [4]:
max(inputs)

7

In [5]:
min(a)

1

In [14]:
a.shape == vector1.shape

True

In [22]:
a=a.reshape(1,3)

In [23]:
a.shape

(1, 3)

In [24]:
a.shape[1]

3

In [33]:
sum(inputs)

10

In [35]:
len(inputs)

3

In [36]:
a.average

AttributeError: 'numpy.ndarray' object has no attribute 'average'

In [37]:
np.average(inputs)

3.3333333333333335